import type { Road, Report, Shelter, Weather, Alert } from "./types";

// Approximate polylines around Marikina City. Coordinates are illustrative,
// good enough for a working demo map; swap for real OSM geometry later.
export const MOCK_ROADS: Road[] = [
  {
    id: "jp-rizal",
    name: "J.P. Rizal Street",
    barangay: "Barangka",
    path: [
      [14.6360, 121.0930],
      [14.6410, 121.0980],
      [14.6455, 121.1020],
      [14.6500, 121.1055],
    ],
  },
  {
    id: "shoe-ave",
    name: "Shoe Avenue",
    barangay: "San Roque",
    path: [
      [14.6490, 121.0985],
      [14.6520, 121.1035],
      [14.6545, 121.1085],
    ],
  },
  {
    id: "gil-fernando",
    name: "Gil Fernando Avenue",
    barangay: "San Roque",
    path: [
      [14.6300, 121.1090],
      [14.6360, 121.1110],
      [14.6420, 121.1130],
      [14.6480, 121.1150],
    ],
  },
  {
    id: "sumulong-hwy",
    name: "Sumulong Highway",
    barangay: "Sto. Niño",
    path: [
      [14.6320, 121.1000],
      [14.6420, 121.1090],
      [14.6520, 121.1180],
      [14.6620, 121.1260],
    ],
  },
  {
    id: "marcos-hwy",
    name: "Marcos Highway",
    barangay: "Calumpang",
    path: [
      [14.6220, 121.0930],
      [14.6250, 121.1030],
      [14.6280, 121.1140],
      [14.6300, 121.1260],
    ],
  },
  {
    id: "bonifacio-ave",
    name: "A. Bonifacio Avenue",
    barangay: "Barangka",
    path: [
      [14.6540, 121.0940],
      [14.6580, 121.1000],
      [14.6620, 121.1060],
    ],
  },
  {
    id: "katipunan-ext",
    name: "Katipunan Extension",
    barangay: "Concepcion Uno",
    path: [
      [14.6600, 121.1080],
      [14.6660, 121.1140],
      [14.6720, 121.1200],
    ],
  },
  {
    id: "riverbanks",
    name: "Riverbanks Road",
    barangay: "Barangka",
    path: [
      [14.6420, 121.0870],
      [14.6480, 121.0900],
      [14.6540, 121.0930],
    ],
  },

  // --- Surrounding cities (Marikina River basin) ---
  {
    id: "ortigas-ext-cainta",
    name: "Ortigas Avenue Extension",
    barangay: "Cainta, Rizal",
    path: [
      [14.5760, 121.1180],
      [14.5810, 121.1235],
      [14.5865, 121.1285],
    ],
  },
  {
    id: "manila-east-taytay",
    name: "Manila East Road",
    barangay: "Taytay, Rizal",
    path: [
      [14.5580, 121.1320],
      [14.5645, 121.1360],
      [14.5710, 121.1400],
    ],
  },
  {
    id: "c-raymundo-pasig",
    name: "C. Raymundo Avenue",
    barangay: "Pasig City",
    path: [
      [14.5680, 121.0860],
      [14.5725, 121.0920],
      [14.5765, 121.0985],
    ],
  },
  {
    id: "gen-luna-sanmateo",
    name: "Gen. Luna Street",
    barangay: "San Mateo, Rizal",
    path: [
      [14.6960, 121.1180],
      [14.7015, 121.1210],
      [14.7065, 121.1245],
    ],
  },
  {
    id: "e-rodriguez-montalban",
    name: "E. Rodriguez Highway",
    barangay: "Rodriguez (Montalban), Rizal",
    path: [
      [14.7250, 121.1330],
      [14.7320, 121.1385],
      [14.7390, 121.1435],
    ],
  },
  {
    id: "sumulong-antipolo",
    name: "Sumulong Highway (Antipolo)",
    barangay: "Antipolo City, Rizal",
    path: [
      [14.6180, 121.1600],
      [14.6120, 121.1685],
      [14.6055, 121.1760],
    ],
  },
  {
    id: "batasan-qc",
    name: "Batasan Road",
    barangay: "Quezon City",
    path: [
      [14.6900, 121.0900],
      [14.6850, 121.0960],
      [14.6800, 121.1020],
    ],
  },
  {
    id: "tumana-bridge",
    name: "Tumana Bridge",
    barangay: "Marikina / Quezon City",
    path: [
      [14.6560, 121.0820],
      [14.6580, 121.0860],
      [14.6600, 121.0900],
    ],
  },
];

const now = Date.now();
const minsAgo = (m: number) => now - m * 60 * 1000;

// ============================================================================
// SIMULATED / DEMO DATA — one coherent flood scenario for Marikina City.
// A period of heavy rainfall has caused localized flooding. These reports are
// FICTIONAL and for demonstration only; they are not real-time conditions.
// Reporter names are fictional demo users (no real personal information).
// The mix intentionally covers: verified / pending / disputed / expired,
// different flood depths, and cases where VEHICLE and PEDESTRIAN passability
// differ. Everything below is consumed by the map, navigation, AI, alerts,
// and the LGU/DRRM dashboard so the whole system stays internally consistent.
// ============================================================================
export const MOCK_REPORTS: Report[] = [
  // 1) VERIFIED · knee-deep · impassable to vehicles AND unsafe to walk.
  //    This makes J.P. Rizal the "HIGH risk" shortest-route hazard in the demo.
  {
    id: "r1",
    userId: "u2",
    userName: "Maria Santos",
    gps: [14.6455, 121.1020],
    roadId: "jp-rizal",
    roadName: "J.P. Rizal Street",
    barangay: "Barangka",
    createdAt: minsAgo(3),
    vehicle: "not_passable",
    pedestrian: "unsafe",
    floodLevel: "knee",
    hazards: ["strong_current"],
    photoUrl: undefined,
    notes: "Water reached knee level near the intersection. Motorcycles cannot pass.",
    ai: {
      floodVisible: true,
      consistentWithReport: true,
      imageQualityOk: true,
      confidence: "high",
      note: "Flooding appears visible. Evidence consistent with the submitted report.",
    },
    confirmations: [
      { id: "c1", userId: "u3", vote: "still_accurate", at: minsAgo(2) },
      { id: "c2", userId: "u4", vote: "still_accurate", at: minsAgo(1) },
    ],
    status: "verified",
  },
  // 2) VERIFIED · ankle-deep · caution — the "MODERATE risk" alternative.
  {
    id: "r2",
    userId: "u5",
    userName: "Alex Reyes",
    gps: [14.6520, 121.1035],
    roadId: "shoe-ave",
    roadName: "Shoe Avenue",
    barangay: "San Roque",
    createdAt: minsAgo(8),
    vehicle: "caution",
    pedestrian: "caution",
    floodLevel: "ankle",
    hazards: ["slippery"],
    notes: "Ankle-deep water, passable slowly.",
    ai: {
      floodVisible: true,
      consistentWithReport: true,
      imageQualityOk: true,
      confidence: "medium",
      note: "Shallow flooding visible, consistent with an ankle-deep report.",
    },
    confirmations: [{ id: "c3", userId: "u6", vote: "still_accurate", at: minsAgo(5) }],
    status: "verified",
  },
  // 3) VERIFIED · clear · the recommended LOWER-RISK route in the demo.
  {
    id: "r3",
    userId: "u7",
    userName: "Andrea Garcia",
    gps: [14.6420, 121.1130],
    roadId: "gil-fernando",
    roadName: "Gil Fernando Avenue",
    barangay: "San Roque",
    createdAt: minsAgo(7),
    vehicle: "passable",
    pedestrian: "lower_risk",
    floodLevel: "none",
    hazards: [],
    notes: "Road is clear, no flooding observed.",
    confirmations: [{ id: "c3b", userId: "u6", vote: "still_accurate", at: minsAgo(4) }],
    status: "verified",
  },
  // 4) VERIFIED · waist-deep · impassable (dramatic hazard).
  {
    id: "r4",
    userId: "u8",
    userName: "Miguel Ramos",
    gps: [14.6520, 121.1180],
    roadId: "sumulong-hwy",
    roadName: "Sumulong Highway",
    barangay: "Sto. Niño",
    createdAt: minsAgo(12),
    vehicle: "not_passable",
    pedestrian: "unsafe",
    floodLevel: "waist",
    hazards: ["strong_current", "debris"],
    notes: "Waist-deep near the bridge approach, strong current.",
    ai: {
      floodVisible: true,
      consistentWithReport: true,
      imageQualityOk: true,
      confidence: "high",
      note: "Deep flooding and debris visible.",
    },
    confirmations: [
      { id: "c4", userId: "u9", vote: "still_accurate", at: minsAgo(10) },
      { id: "c5", userId: "u10", vote: "still_accurate", at: minsAgo(6) },
      { id: "c6", userId: "u11", vote: "still_accurate", at: minsAgo(3) },
    ],
    status: "verified",
  },
  // 5) KEY DEMO: VEHICLE passable but PEDESTRIAN unsafe (why we split them).
  {
    id: "r9",
    userId: "u20",
    userName: "Juan Dela Cruz",
    gps: [14.6580, 121.1000],
    roadId: "bonifacio-ave",
    roadName: "A. Bonifacio Avenue",
    barangay: "Barangka",
    createdAt: minsAgo(5),
    vehicle: "passable",
    pedestrian: "unsafe",
    floodLevel: "knee",
    hazards: ["strong_current"],
    notes:
      "Cars can still cross slowly, but the current is too strong for people on foot.",
    ai: {
      floodVisible: true,
      consistentWithReport: true,
      imageQualityOk: true,
      confidence: "medium",
      note: "Moving water visible; consistent with a walk-unsafe but drivable road.",
    },
    confirmations: [{ id: "c11", userId: "u21", vote: "still_accurate", at: minsAgo(3) }],
    status: "verified",
  },
  // 6) DISPUTED: community disagrees — must NOT be treated like a verified report.
  {
    id: "r10",
    userId: "u22",
    userName: "Alex Reyes",
    gps: [14.6280, 121.1140],
    roadId: "marcos-hwy",
    roadName: "Marcos Highway",
    barangay: "Calumpang",
    createdAt: minsAgo(18),
    vehicle: "not_passable",
    pedestrian: "unsafe",
    floodLevel: "knee",
    hazards: [],
    notes: "Reported knee-deep, but several residents say the road is actually passable.",
    confirmations: [
      { id: "c12", userId: "u23", vote: "still_accurate", at: minsAgo(16) },
      { id: "c13", userId: "u24", vote: "appears_incorrect", at: minsAgo(12) },
      { id: "c14", userId: "u25", vote: "appears_incorrect", at: minsAgo(10) },
      { id: "c15", userId: "u26", vote: "appears_incorrect", at: minsAgo(8) },
      { id: "c16", userId: "u27", vote: "situation_changed", at: minsAgo(6) },
    ],
    status: "disputed",
  },
  // 7) PENDING: awaiting LGU review — used for the verification workflow demo.
  {
    id: "r11",
    userId: "u28",
    userName: "Andrea Garcia",
    gps: [14.6480, 121.0900],
    roadId: "riverbanks",
    roadName: "Riverbanks Road",
    barangay: "Barangka",
    createdAt: minsAgo(4),
    vehicle: "caution",
    pedestrian: "caution",
    floodLevel: "ankle",
    hazards: ["slippery"],
    notes: "Water rising slowly near the riverside. Please verify.",
    confirmations: [],
    status: "pending",
  },
  // 8) EXPIRED: ~3 hours old — the engine ignores it for current routing.
  {
    id: "r12",
    userId: "u29",
    userName: "Miguel Ramos",
    gps: [14.6660, 121.1140],
    roadId: "katipunan-ext",
    roadName: "Katipunan Extension",
    barangay: "Concepcion Uno",
    createdAt: minsAgo(180),
    vehicle: "not_passable",
    pedestrian: "unsafe",
    floodLevel: "knee",
    hazards: [],
    notes: "Older report — conditions may have changed since it was submitted.",
    confirmations: [],
    status: "expired",
  },
  // 9) VERIFIED · dramatic · damaged bridge hazard.
  {
    id: "r13",
    userId: "u30",
    userName: "Juan Dela Cruz",
    gps: [14.6580, 121.0860],
    roadId: "tumana-bridge",
    roadName: "Tumana Bridge",
    barangay: "Marikina / Quezon City",
    createdAt: minsAgo(11),
    vehicle: "not_passable",
    pedestrian: "unsafe",
    floodLevel: "waist",
    hazards: ["damaged_bridge", "strong_current"],
    notes: "River very high near the bridge. Authorities restricting crossing.",
    confirmations: [
      { id: "c17", userId: "u31", vote: "still_accurate", at: minsAgo(8) },
      { id: "c18", userId: "u32", vote: "still_accurate", at: minsAgo(5) },
    ],
    status: "verified",
  },

  // --- Surrounding cities (same flood event) ---
  {
    id: "r5",
    userId: "u12",
    userName: "Maria Santos",
    gps: [14.5810, 121.1235],
    roadId: "ortigas-ext-cainta",
    roadName: "Ortigas Avenue Extension",
    barangay: "Cainta, Rizal",
    createdAt: minsAgo(6),
    vehicle: "not_passable",
    pedestrian: "unsafe",
    floodLevel: "knee",
    hazards: ["heavy_traffic", "strong_current"],
    notes: "Knee-deep near the junction, vehicles stalled.",
    ai: {
      floodVisible: true,
      consistentWithReport: true,
      imageQualityOk: true,
      confidence: "high",
      note: "Flooding visible at a busy junction.",
    },
    confirmations: [
      { id: "c7", userId: "u13", vote: "still_accurate", at: minsAgo(4) },
      { id: "c8", userId: "u14", vote: "still_accurate", at: minsAgo(2) },
    ],
    status: "verified",
  },
  {
    id: "r6",
    userId: "u15",
    userName: "Alex Reyes",
    gps: [14.7015, 121.1210],
    roadId: "gen-luna-sanmateo",
    roadName: "Gen. Luna Street",
    barangay: "San Mateo, Rizal",
    createdAt: minsAgo(14),
    vehicle: "caution",
    pedestrian: "caution",
    floodLevel: "ankle",
    hazards: ["slippery"],
    notes: "Ankle-deep, passable with care.",
    confirmations: [{ id: "c9", userId: "u16", vote: "still_accurate", at: minsAgo(9) }],
    status: "pending",
  },
  {
    id: "r7",
    userId: "u17",
    userName: "Andrea Garcia",
    gps: [14.6120, 121.1685],
    roadId: "sumulong-antipolo",
    roadName: "Sumulong Highway (Antipolo)",
    barangay: "Antipolo City, Rizal",
    createdAt: minsAgo(20),
    vehicle: "passable",
    pedestrian: "lower_risk",
    floodLevel: "none",
    hazards: [],
    notes: "Clear on the uphill stretch.",
    confirmations: [],
    status: "pending",
  },
  {
    id: "r8",
    userId: "u18",
    userName: "Miguel Ramos",
    gps: [14.5725, 121.0920],
    roadId: "c-raymundo-pasig",
    roadName: "C. Raymundo Avenue",
    barangay: "Pasig City",
    createdAt: minsAgo(9),
    vehicle: "not_passable",
    pedestrian: "unsafe",
    floodLevel: "waist",
    hazards: ["strong_current"],
    notes: "Waist-deep along the low section.",
    ai: {
      floodVisible: true,
      consistentWithReport: true,
      imageQualityOk: true,
      confidence: "high",
      note: "Deep flooding visible.",
    },
    confirmations: [{ id: "c10", userId: "u19", vote: "still_accurate", at: minsAgo(5) }],
    status: "verified",
  },
];

// SIMULATED / DEMO shelter data. Occupancy values are consistent
// (occupancy ≤ capacity). Contact numbers are placeholders.
export const MOCK_SHELTERS: Shelter[] = [
  {
    id: "s1",
    name: "Marikina Sports Center",
    location: [14.6340, 121.0960],
    barangay: "Sta. Elena",
    status: "open",
    capacity: 800,
    occupancy: 210,
    contact: "(02) 8646-2360",
  },
  {
    id: "s2",
    // Nearly full in the demo (270/300 = 90%) — UI shows a "Nearly full" hint.
    name: "Barangka Elementary School",
    location: [14.6470, 121.0920],
    barangay: "Barangka",
    status: "open",
    capacity: 300,
    occupancy: 270,
    contact: "(02) 8942-1101",
  },
  {
    id: "s3",
    name: "Concepcion Integrated School",
    location: [14.6660, 121.1120],
    barangay: "Concepcion Uno",
    status: "full",
    capacity: 400,
    occupancy: 400,
    contact: "(02) 8941-2233",
  },
  {
    id: "s4",
    name: "Sto. Niño Covered Court",
    location: [14.6380, 121.1040],
    barangay: "Sto. Niño",
    status: "open",
    capacity: 250,
    occupancy: 90,
    contact: "(02) 8997-5544",
  },

  // --- Surrounding cities ---
  {
    id: "s5",
    name: "Cainta Municipal Gymnasium",
    location: [14.5790, 121.1220],
    barangay: "Cainta, Rizal",
    status: "open",
    capacity: 500,
    occupancy: 260,
    contact: "(02) 8656-1101",
  },
  {
    id: "s6",
    name: "San Mateo Sports Complex",
    location: [14.6980, 121.1200],
    barangay: "San Mateo, Rizal",
    status: "open",
    capacity: 450,
    occupancy: 120,
    contact: "(02) 8942-2020",
  },
  {
    id: "s7",
    name: "Pasig Rainforest Evacuation Hub",
    location: [14.5700, 121.0900],
    barangay: "Pasig City",
    status: "full",
    capacity: 600,
    occupancy: 600,
    contact: "(02) 8643-1111",
  },
  {
    id: "s8",
    name: "Antipolo City Hall Multi-Purpose Hall",
    location: [14.6255, 121.1720],
    barangay: "Antipolo City, Rizal",
    status: "open",
    capacity: 700,
    occupancy: 180,
    contact: "(02) 8697-3030",
  },
  {
    id: "s9",
    name: "Rodriguez (Montalban) Covered Court",
    location: [14.7310, 121.1380],
    barangay: "Rodriguez (Montalban), Rizal",
    status: "open",
    capacity: 400,
    occupancy: 95,
    contact: "(02) 8998-7070",
  },
  {
    id: "s10",
    // Closed in the demo (undergoing assessment) — navigation must not send
    // evacuees here, and the AI should mention it is closed.
    name: "Nangka Barangay Hall",
    location: [14.6720, 121.1050],
    barangay: "Nangka",
    status: "closed",
    capacity: 200,
    occupancy: 0,
    contact: "(02) 8941-8080",
  },
];

// SIMULATED / DEMO weather (not a live feed in this dataset).
export const MOCK_WEATHER: Weather = {
  rainfallMmHr: 18,
  windKph: 34,
  condition: "Heavy rain",
  forecastNote: "Simulated demo: heavy rainfall expected to continue for the next 2-3 hours.",
};

// SIMULATED / DEMO alerts. Covers weather, flood, road closure, pedestrian
// safety, evacuation/shelter, official LGU advisory, and community/report
// types. `advisory` = OFFICIAL LGU/DRRM; `report_request`/`flood` are
// community-sourced; `system` is app information.
export const MOCK_ALERTS: Alert[] = [
  {
    id: "a0",
    kind: "system",
    title: "You are viewing DEMO / SIMULATED data",
    body: "This is a demonstration scenario. Reports, alerts, weather, shelters, and routes are simulated and do not reflect real-time conditions in Marikina City.",
    at: minsAgo(30),
    read: false,
  },
  {
    id: "a1",
    kind: "weather",
    title: "Heavy rain expected (Demo)",
    body: "Simulated advisory: heavy rainfall over Marikina for the next few hours.",
    at: minsAgo(20),
    read: false,
  },
  {
    id: "a2",
    kind: "flood",
    title: "Flood conditions reported nearby (Demo)",
    body: "Multiple community reports of knee-to-waist deep flooding along Sumulong Highway and J.P. Rizal.",
    at: minsAgo(10),
    read: false,
  },
  {
    id: "a5",
    kind: "road",
    title: "Road closure — Tumana Bridge (Demo)",
    body: "Tumana Bridge crossing restricted due to high river levels. Avoid the area and use alternate routes.",
    at: minsAgo(8),
    read: false,
  },
  {
    id: "a6",
    kind: "route",
    title: "Pedestrian safety notice (Demo)",
    body: "A. Bonifacio Avenue is reported drivable but UNSAFE for pedestrians due to strong current. Walkers should choose another route.",
    at: minsAgo(7),
    read: false,
  },
  {
    id: "a3",
    kind: "report_request",
    title: "Current road-condition report requested (Demo)",
    body: "If you are in a safe location and can observe the road, please submit a current report.",
    at: minsAgo(9),
    read: false,
  },
  {
    id: "a7",
    kind: "advisory",
    title: "Evacuation shelters open (Official · Demo)",
    body: "Marikina Sports Center and Sto. Niño Covered Court are open with available capacity. Concepcion Integrated School is now full.",
    at: minsAgo(6),
    read: false,
  },
  {
    id: "a4",
    kind: "advisory",
    title: "LGU/DRRM announcement (Official · Demo)",
    body: "Residents in low-lying barangays advised to prepare for possible evacuation.",
    at: minsAgo(6),
    read: true,
  },
];
